#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS24_CustomizationScreen

#include "Basic.hpp"

#include "BPS24_CustomizationScreen_classes.hpp"
#include "BPS24_CustomizationScreen_parameters.hpp"


namespace SDK
{

// Function BPS24_CustomizationScreen.BPS24_CustomizationScreen_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UBPS24_CustomizationScreen_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS24_CustomizationScreen_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS24_CustomizationScreen.BPS24_CustomizationScreen_C.ExecuteUbergraph_BPS24_CustomizationScreen
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS24_CustomizationScreen_C::ExecuteUbergraph_BPS24_CustomizationScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS24_CustomizationScreen_C", "ExecuteUbergraph_BPS24_CustomizationScreen");

	Params::BPS24_CustomizationScreen_C_ExecuteUbergraph_BPS24_CustomizationScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

