#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_UnstableBow_Intro

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_UnstableBow_Intro.GCN_UnstableBow_Intro_C
// 0x0000 (0x0210 - 0x0210)
class UGCN_UnstableBow_Intro_C final : public UFortGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_UnstableBow_Intro_C">();
	}
	static class UGCN_UnstableBow_Intro_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_UnstableBow_Intro_C>();
	}
};
static_assert(alignof(UGCN_UnstableBow_Intro_C) == 0x000008, "Wrong alignment on UGCN_UnstableBow_Intro_C");
static_assert(sizeof(UGCN_UnstableBow_Intro_C) == 0x000210, "Wrong size on UGCN_UnstableBow_Intro_C");

}

