#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GrindRail_TipOptions

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct GrindRail_TipOptions.GrindRail_TipOptions
// 0x0002 (0x0002 - 0x0000)
struct FGrindRail_TipOptions final
{
public:
	bool                                          CapStartTip_14_BE02D3114E8D77DE637964B9E3B9BF78;   // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CapEndTip_15_1938E7644D71206872041C932B0DF129;     // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FGrindRail_TipOptions) == 0x000001, "Wrong alignment on FGrindRail_TipOptions");
static_assert(sizeof(FGrindRail_TipOptions) == 0x000002, "Wrong size on FGrindRail_TipOptions");
static_assert(offsetof(FGrindRail_TipOptions, CapStartTip_14_BE02D3114E8D77DE637964B9E3B9BF78) == 0x000000, "Member 'FGrindRail_TipOptions::CapStartTip_14_BE02D3114E8D77DE637964B9E3B9BF78' has a wrong offset!");
static_assert(offsetof(FGrindRail_TipOptions, CapEndTip_15_1938E7644D71206872041C932B0DF129) == 0x000001, "Member 'FGrindRail_TipOptions::CapEndTip_15_1938E7644D71206872041C932B0DF129' has a wrong offset!");

}

