#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseSimulationMetadata_0

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// VerseClass VerseSimulationMetadata.Simulation
// 0x0000 (0x0028 - 0x0028)
class VerseSimulationMetadata_0::USimulation final : public UObject
{
public:
	void _InitCDO();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"VerseClass VerseSimulationMetadata.Simulation", true>();
	}
	static class VerseSimulationMetadata_0::USimulation* GetDefaultObj()
	{
		return GetDefaultObjImpl<VerseSimulationMetadata_0::USimulation>();
	}
};
static_assert(alignof(VerseSimulationMetadata_0::USimulation) == 0x000008, "Wrong alignment on VerseSimulationMetadata_0::USimulation");
static_assert(sizeof(VerseSimulationMetadata_0::USimulation) == 0x000028, "Wrong size on VerseSimulationMetadata_0::USimulation");

}

